add jox test script, jox env variables, and update oai charms

diff --git a/charms/trusty/oai-epc/hooks/install b/charms/trusty/oai-epc/hooks/install
--- a/charms/trusty/oai-epc/hooks/install
+++ b/charms/trusty/oai-epc/hooks/install
@@ -33,6 +33,140 @@
 # brief install the oai-epc from the openairinterface git repository
 # author  navid.nikaein@eurecom.fr and A. B. Molini   
 
+install_packages(){
+    gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
+    if [ ! $gitAlreadyInstalled -eq 1 ]; then 
+	# If git is NOT installed
+	apt-get install -y  --force-yes  git 
+	# Ensure necessary git dependency exist.
+    fi
+    atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
+    if [ ! $atAlreadyInstalled -eq 1 ]; then 
+	# If at command is NOT installed
+	apt-get install -y --force-yes at
+	# Ensure at command exists to let juju reschedule this hook after rebooting the machine.
+    fi
+    virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
+    if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
+	apt-get install -y --force-yes virt-what
+    fi
+
+    #Mysql-server simply because we want resolveip tool
+    PASSWORD="linux"
+    echo "mysql-server mysql-server/root_password password $PASSWORD" | debconf-set-selections
+    echo "mysql-server mysql-server/root_password_again password $PASSWORD" | debconf-set-selections
+
+    apt install -y mysql-client
+}
+
+clone_repro(){
+    juju-log "Fetching and installing openair5G EPC"
+    status-set maintenance "Fetching and installing Openair5G EPC"
+    
+    echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
+    #everytime refresh the installation 
+    if [ -d "$openair_path"  ]; then
+	#juju-log "Removing the installation directory"
+	#rm -rf $openair_path
+	juju-log "Updating the installation directory"
+	cd $openair_path 
+	git reset --hard HEAD
+	git checkout $branch 
+	git pull
+	shopt -s nocasematch 
+	if [[ "$revision" != "HEAD" ]]; then  
+	    git checkout $revision
+	fi
+	cd -
+    else
+	#Save the current hosts file
+	cp -f /etc/hosts /home
+	git clone https://gitlab.eurecom.fr/oai/openair-cn.git $openair_path
+	cd $openair_path
+	git checkout $branch 
+	shopt -s nocasematch
+	if [[ "$revision" != "HEAD" ]]; then  
+	    git checkout $revision
+	fi 
+	cd -
+    fi
+  
+    #We don't need phpmyadmin in the installation as it is provided by phpmyadmin charm
+    #sed -i "s/phpmyadmin/#phpmyadmin/" $tools_path/build_helper
+    sed -i '/phpmyadmin/d' $tools_path/build_helper
+    sed -i -r "s/(check_kernel_release_and_install_xtables_addons_oai[^()]+)/#\1/" $tools_path/build_helper
+
+}
+
+juju_install_kernel(){
+
+    juju-log "Check the kernel and update if required"
+
+    if [ "$machine_type"  == "lxc" -o "$machine_type" == "docker" ]; then 
+	juju-log "Can't install the required kernel in $machine_type env. Either deploy oai-epc with kvm or make sure that the host has the required version and kernel modules".
+	status-set error "Can't install the required kernel 3.19"
+    else 
+	if  [ "$machine_type"  == "" ] ; then 
+	    juju-log "Please install kerenel version 3.19 on the host".
+	else 
+	    check_current_kernel
+	    if [[ $REQUIRED_KERNEL_IS_INSTALLED == false ]]; then
+		if [ "$(cat $CHARM_DIR/.reboot)" != "reboot" ]; then  
+		    juju-log "installing the required kernel and reboot"
+		    status-set maintenance "installing the required kernel and rebooting"
+		    install_required_kernel
+  		    echo "reboot" > $CHARM_DIR/.reboot 
+		    juju-reboot --now
+		else 
+		    juju-log "Can't install the required kernel."
+		    status-set error "Can't install the required kernel"
+		fi 
+	    fi
+	fi 
+    fi
+}
+
+update_hostname(){
+  HOSTNAME=`echo $JUJU_UNIT_NAME | sed 's|/|-|'`
+  echo "$HOSTNAME" > /etc/hostname
+  hostname $HOSTNAME
+  echo "127.0.0.1 `hostname`" > /etc/hosts
+}
+
+configure_hosts(){
+  realm=`config-get realm`
+  #define fqdn for MME
+  if [ -z "$(grep -o "`hostname`.$realm" /etc/hosts)" ]; then
+     echo 127.0.0.1 localhost > /etc/hosts
+     echo 127.0.0.1 `hostname`.$realm `hostname` mme >> /etc/hosts
+  fi
+}
+
+build_epc(){
+    juju-log "Build EPC and install required packages"
+
+    $build_run_scripts/build_epc -c -i -f >& /srv/.build_epc_install.log
+    #$build_run_scripts/build_epc -t -f 
+    
+    source $tools_path/build_helper
+    install_xtables_addons_oai 1
+    
+    #In the epc.conf there will be the local hostname as HSS_HOSTNAME, basically
+    #like HSS was on the same machine of EPC. It is the default if you don't
+    #give any hss name in input to build_epc script.
+    #So we can't start the final executable because we would get an error 
+    #so we need to wait for a relation.
+
+    $build_run_scripts/build_epc -c -H "unknown.$realm" >& /srv/.build_epc_compile.log
+    status=$?
+    if [ "$status" != 0 ]; then 
+	$build_run_scripts/build_epc -c -i -f
+	#  $build_run_scripts/build_epc -t -f 
+	$build_run_scripts/build_epc -c -H "unknown.$realm"
+    fi 
+
+}
+
 set -eux
 
 export DEBIAN_FRONTEND=noninteractive
@@ -46,102 +180,18 @@ revision=`config-get revision`
 echo "$branch" > $CHARM_DIR/.branch
 echo "$revision" > $CHARM_DIR/.revision
 
-status-set maintenance "Fetching and installing Openair4G"
+update_hostname
 
-gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
-if [ ! $gitAlreadyInstalled -eq 1 ]; then 
-   # If git is NOT installed
-   apt-get install -y  --force-yes  git 
-   # Ensure necessary git dependency exist.
-fi
-atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
-if [ ! $atAlreadyInstalled -eq 1 ]; then 
-   # If at command is NOT installed
-   apt-get install -y --force-yes at
-   # Ensure at command exists to let juju reschedule this hook after rebooting the machine.
-fi
-virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
-if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
-   apt-get install -y --force-yes virt-what
-fi
+install_packages
 machine_type=`virt-what`
 
-juju-log "Fetching and installing openair5G EPC"
-status-set maintenance "Fetching and installing Openair5G EPC"
+clone_repro
 
-echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
-#everytime refresh the installation 
-if [ -d "$openair_path"  ]; then
-   #juju-log "Removing the installation directory"
-   #rm -rf $openair_path
-    juju-log "Updating the installation directory"
-    cd $openair_path 
-    git reset --hard HEAD
-    git checkout $branch 
-    git pull
-    shopt -s nocasematch 
-    if [[ "$revision" != "HEAD" ]]; then  
-	git checkout $revision
-    fi
-    cd -
-else
-   #Save the current hosts file
-   cp -f /etc/hosts /home
-   git clone https://gitlab.eurecom.fr/oai/openair-cn.git $openair_path
-   cd $openair_path
-   git checkout $branch 
-   shopt -s nocasematch
-   if [[ "$revision" != "HEAD" ]]; then  
-       git checkout $revision
-   fi 
-   cd -
-fi
+juju_install_kernel
 
-#We don't need phpmyadmin because the database will be somewhere else.
-#sed -i "s/phpmyadmin/#phpmyadmin/" $tools_path/build_helper
-sed -i "/phpmyadmin/d" $tools_path/build_helper
+configure_hosts
 
-status-set maintenance "Installing some dependencies"
-
-#mysql-server needed for installing resolveip tool, we don't actually use mysql-server
-echo "mysql-server mysql-server/root_password password linux" | debconf-set-selections
-echo "mysql-server mysql-server/root_password_again password linux" | debconf-set-selections
-sudo apt-get install -y mysql-server
-
-juju-log "Check the kernel and update if required"
-
-
-if [ "$machine_type"  == "lxc" -o "$machine_type" == "docker" ]; then 
-    juju-log "Can't install the required kernel in $machine_type env. Either deploy oai-epc with kvm or make sure that the host has the required version and kernel modules".
-    status-set error "Can't install the required kernel 3.19"
-else 
-    if  [ "$machine_type"  == "" ] ; then 
-	juju-log "Please install kerenel version 3.19 on the host".
-    else 
-	check_current_kernel
-	if [[ $REQUIRED_KERNEL_IS_INSTALLED == false ]]; then
-	    if [ "$(cat $CHARM_DIR/.reboot)" != "reboot" ]; then  
-		juju-log "installing the required kernel and reboot"
-		status-set maintenance "installing the required kernel and rebooting"
-		install_required_kernel
-  		echo "reboot" > $CHARM_DIR/.reboot 
-		juju-reboot --now
-	    else 
-		juju-log "Can't install the required kernel."
-		status-set error "Can't install the required kernel"
-	    fi 
-	fi
-    fi 
-fi
-
-juju-log "Build process and package installation"
-sed -i -r "s/(check_kernel_release_and_install_xtables_addons_oai[^()]+)/#\1/" $tools_path/build_helper
-
-$build_run_scripts/build_epc -c -i -f >& /srv/.build_epc_install.log
-#$build_run_scripts/build_epc -t -f 
-
-source $tools_path/build_helper
-install_xtables_addons_oai 1
+build_epc
 
 
 if [ ! -f $CHARM_DIR/.tac_list ]; then
@@ -152,30 +202,6 @@ fi
 juju-log "Add mme-gw init script"
 cp $CHARM_DIR/files/mme_gw /etc/init/mme_gw.conf
 
-realm=`config-get realm`
-echo "$realm" > $CHARM_DIR/.realm
-#define fqdn for MME
-if [ -z "$(grep -o "`hostname`.$realm" /etc/hosts)" ]; then
-   echo 127.0.0.1 localhost > /etc/hosts
-   echo 127.0.1.1 `hostname`.$realm `hostname` mme >> /etc/hosts
-fi
-
-machine_realm=`hostname`.$realm
-#In the epc.conf there will be the local hostname as HSS_HOSTNAME, basically
-#like HSS was on the same machine of EPC. It is the default if you don't
-#give any hss name in input to build_epc script.
-#So we can't start the final executable because we would get an error 
-#so we need to wait for a relation.
-status-set maintenance "Building EPC"
-
-
-$build_run_scripts/build_epc -c -H "unknown.$realm" >& /srv/.build_epc_compile.log
-status=$?
-if [ "$status" != 0 ]; then 
-    $build_run_scripts/build_epc -c -i -f
-  #  $build_run_scripts/build_epc -t -f 
-    $build_run_scripts/build_epc -c -H "unknown.$realm"
-fi 
 
 if [ ! -f /usr/local/bin/mme_gw ] ; then
  status-set error "mme_gw compilation failed! Try increasing the size of Virtual Memory if only 512M and retry!"
diff --git a/charms/trusty/oai-hss/hooks/install b/charms/trusty/oai-hss/hooks/install
--- a/charms/trusty/oai-hss/hooks/install
+++ b/charms/trusty/oai-hss/hooks/install
@@ -33,6 +33,125 @@
 # brief install the oai-hss from the openairinterface git repository
 # author  navid.nikaein@eurecom.fr and A. B. Molini   
 
+install_packages(){
+    status-set maintenance "Installing some dependencies"
+    
+    gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
+    if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
+	apt-get install -y --force-yes git  # Ensure necessary git dependency exist.
+    fi
+    atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
+    if [ ! $atAlreadyInstalled -eq 1 ]; then 
+	apt-get install -y --force-yes at
+    fi
+    virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
+    if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
+	apt-get install -y --force-yes virt-what
+    fi 
+    
+    PASSWORD="linux"
+    echo "mysql-server mysql-server/root_password password $PASSWORD" | debconf-set-selections
+    echo "mysql-server mysql-server/root_password_again password $PASSWORD" | debconf-set-selections
+
+    apt install -y mysql-client
+}
+
+clone_repro(){
+
+    juju-log "Fetching and installing OpenAirInterface HSS"
+    status-set maintenance "Fetching and installing OpenAirInterface HSS"
+    
+    echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
+    
+    if [ -d "$openair_path"  ]; then
+	#   juju-log "Removing the installation directory"
+	#   rm -rf $openair_path
+	juju-log "Updating the installation directory"
+	cd $openair_path
+	git reset --hard HEAD 
+	git checkout $branch 
+	git pull 
+	shopt -s nocasematch
+	if [[ "$revision" != "HEAD" ]]; then 
+	    git checkout $revision
+	fi 
+	cd -
+    else
+	#Save the current hosts file
+	cp -f /etc/hosts /home
+	git clone https://gitlab.eurecom.fr/oai/openair-cn.git $openair_path
+	cd $openair_path
+	git checkout $branch
+	shopt -s nocasematch
+	if [[ "$revision" != "HEAD" ]]; then 
+	    git checkout $revision
+	fi 
+	cd -
+    fi
+  
+    #We don't need phpmyadmin in the installation as it is provided by phpmyadmin charm
+    #sed -i "s/phpmyadmin/#phpmyadmin/" $tools_path/build_helper
+    sed -i '/phpmyadmin/d' $tools_path/build_helper
+    #we don't either want the low latency kernel for HSS
+    sed -i -r "s/(check_kernel_release_and_install_xtables_addons_oai[^()]+)/#\1/" $tools_path/build_helper  
+    
+}
+
+juju_install_kernel(){
+
+    juju-log "Check the kernel and update if required"
+    
+    if [ "$machine_type"  == "lxc" -o "$machine_type" == "docker" ]; then
+	juju-log "Can't install the required kernel in $machine_type env. Proceed with the current kernel."
+    else  
+	if  [ "$machine_type"  == "" ] ; then 
+	    juju-log "Please install kerenel version 3.19 on the host".
+	else 
+	    check_current_kernel
+	    if [[ $REQUIRED_KERNEL_IS_INSTALLED == false ]]; then
+		# a way to avoid looping for lxc env.
+		if [ "$(cat $CHARM_DIR/.reboot)" != "reboot" ]; then  
+		    echo "reboot" > $CHARM_DIR/.reboot 
+		    juju-log "installing the required kernel and reboot"
+		    status-set maintenance "installing the required kernel and rebooting"
+		    install_required_kernel
+    		    juju-reboot --now
+		else 
+		    juju-log "Failed to install the kernel 3.19. Proceed with the current kernel."
+		fi 
+		#if we reboot now, the install is blocked here and reschedule after the reboot
+		#and xtables will be installed
+	    fi
+	fi
+    fi 
+}
+
+update_hostname(){
+  HOSTNAME=`echo $JUJU_UNIT_NAME | sed 's|/|-|'`
+  echo "$HOSTNAME" > /etc/hostname
+  hostname $HOSTNAME
+  echo "127.0.0.1 `hostname`" > /etc/hosts
+}
+
+configure_hosts(){
+  realm=`config-get realm`
+  #define fqdn for MME
+  if [ -z "$(grep -o "`hostname`.$realm" /etc/hosts)" ]; then
+     echo 127.0.0.1 localhost > /etc/hosts
+     echo 127.0.0.1 `hostname`.$realm `hostname` mme >> /etc/hosts
+  fi
+}
+
+build_hss(){
+    $build_run_scripts/build_hss -c -i -F
+    
+    #I need to avoid to execute create_hss_database because I don't need it
+    #so in files direcotry inside my charm I have the right cmakelists file
+    #cp $CHARM_DIR/files/CMakeLists.txt $hss_path/CMakeLists.txt
+    install -o root -g root -m 0644 $CHARM_DIR/files/CMakeLists.txt $hss_path/CMakeLists.txt
+    $build_run_scripts/build_hss -c -d
+}
+
 set -eux
 
 export DEBIAN_FRONTEND=noninteractive
@@ -46,116 +165,25 @@ revision=`config-get revision`
 echo "$branch" > $CHARM_DIR/.branch
 echo "$revision" > $CHARM_DIR/.revision
 
+update_hostname
 
-gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
-if [ ! $gitAlreadyInstalled -eq 1 ]; then # If git is NOT installed
-   apt-get install -y --force-yes git  # Ensure necessary git dependency exist.
-fi
-atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
-if [ ! $atAlreadyInstalled -eq 1 ]; then 
-   apt-get install -y --force-yes at
-fi
-virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
-if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
-   apt-get install -y --force-yes virt-what
-fi
+install_packages
 machine_type=`virt-what`
 
-juju-log "Fetching and installing OpenAirInterface HSS"
-status-set maintenance "Fetching and installing OpenAirInterface HSS"
+install_packages
 
-echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
+clone_repro
 
-if [ -d "$openair_path"  ]; then
-#   juju-log "Removing the installation directory"
-#   rm -rf $openair_path
-    juju-log "Updating the installation directory"
-    cd $openair_path
-    git reset --hard HEAD 
-    git checkout $branch 
-    git pull 
-    shopt -s nocasematch
-    if [[ "$revision" != "HEAD" ]]; then 
-	git checkout $revision
-    fi 
-    cd -
-else
-   #Save the current hosts file
-   cp -f /etc/hosts /home
-   git clone https://gitlab.eurecom.fr/oai/openair-cn.git $openair_path
-   cd $openair_path
-   git checkout $branch
-   shopt -s nocasematch
-   if [[ "$revision" != "HEAD" ]]; then 
-       git checkout $revision
-   fi 
-   cd -
-fi
+juju_install_kernel
 
-#cp $CHARM_DIR/files/build_helper /srv/openair-cn/BUILD/TOOLS
+configure_hosts
 
-status-set maintenance "Installing some dependencies"
-
-#Mysql-server simply because we want resolveip tool
-PASSWORD="linux"
-echo "mysql-server mysql-server/root_password password $PASSWORD" | debconf-set-selections
-echo "mysql-server mysql-server/root_password_again password $PASSWORD" | debconf-set-selections
-
-#We don't need phpmyadmin in the installation as it is provided by phpmyadmin charm
-#sed -i "s/phpmyadmin/#phpmyadmin/" $tools_path/build_helper
-sed -i '/phpmyadmin/d' $tools_path/build_helper
-#we don't either want the low latency kernel for HSS
-sed -i -r "s/(check_kernel_release_and_install_xtables_addons_oai[^()]+)/#\1/" $tools_path/build_helper
-
-juju-log "Check the kernel and update if required"
-
-if [ "$machine_type"  == "lxc" -o "$machine_type" == "docker" ]; then
-    juju-log "Can't install the required kernel in $machine_type env. Proceed with the current kernel."
-else  
-    if  [ "$machine_type"  == "" ] ; then 
-	juju-log "Please install kerenel version 3.19 on the host".
-    else 
-	check_current_kernel
-	if [[ $REQUIRED_KERNEL_IS_INSTALLED == false ]]; then
-	    # a way to avoid looping for lxc env.
-	    if [ "$(cat $CHARM_DIR/.reboot)" != "reboot" ]; then  
-		echo "reboot" > $CHARM_DIR/.reboot 
-		juju-log "installing the required kernel and reboot"
-		status-set maintenance "installing the required kernel and rebooting"
-		install_required_kernel
-    		juju-reboot --now
-	    else 
-		juju-log "Failed to install the kernel 3.19. Proceed with the current kernel."
-	    fi 
-	    #if we reboot now, the install is blocked here and reschedule after the reboot
-	    #and xtables will be installed
-	fi
-    fi
-fi 
-
-
-$build_run_scripts/build_hss -c -i -F
-#$build_run_scripts/build_epc -c -i -f 
-apt install -y mysql-client
+build_hss
 
 #add the oai_hss init
 juju-log "Add oai_hss init script"
 cp $CHARM_DIR/files/oai_hss /etc/init/oai_hss.conf
 
-
-#define fqdn for HSS
-realm=`config-get realm`
-echo "$realm" > $CHARM_DIR/.realm
-if [ -z "$(grep -o "`hostname`.$realm" /etc/hosts)" ]; then
-   echo 127.0.0.1 localhost > /etc/hosts
-   echo 127.0.1.1 `hostname`.$realm `hostname` >> /etc/hosts
-fi
-
-#I need to avoid to execute create_hss_database because I don't need it
-#so in files direcotry inside my charm I have the right cmakelists file
-#cp $CHARM_DIR/files/CMakeLists.txt $hss_path/CMakeLists.txt
-install -o root -g root -m 0644 $CHARM_DIR/files/CMakeLists.txt $hss_path/CMakeLists.txt
-$build_run_scripts/build_hss -c -d
 
 if [ ! -f /usr/local/bin/oai_hss ] ; then
  status-set error "HSS compilation failed! Try increasing the size of Virtual Memory if only 512M and retry!"
diff --git a/charms/trusty/oai-rrh/hooks/install b/charms/trusty/oai-rrh/hooks/install
--- a/charms/trusty/oai-rrh/hooks/install
+++ b/charms/trusty/oai-rrh/hooks/install
@@ -33,6 +33,158 @@
 # brief install the oai-rrh for different RF target
 # author navid.nikaein@eurecom.fr
 
+install_packages(){
+    gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
+    if [ ! $gitAlreadyInstalled -eq 1 ]; then 
+	# If git is NOT installed
+	apt-get install -y --force-yes git 
+	# Ensure necessary git dependency exist.
+    fi
+    atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
+    if [ ! $atAlreadyInstalled -eq 1 ]; then 
+	# If at command is NOT installed
+	apt-get install -y --force-yes at
+	# Ensure at command exists to let juju reschedule this hook after rebooting the machine.
+    fi
+    virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
+    if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
+	apt-get install -y --force-yes virt-what
+    fi
+    
+}
+
+clone_repro(){
+    juju-log "Fetching and installing openairinterface RRH GW for $hw"
+    status-set maintenance "Fetching and installing openairinterface RRH GW"
+    
+    
+    echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
+    
+    #everytime refresh the installation 
+    if [ -d "$openair_path"  ]; then
+	#juju-log "Removing the installation directory"
+	#rm -rf $openair_path
+	juju-log "Updating the installation directory"
+	cd $openair_path 
+	git reset --hard HEAD
+	git checkout $branch 
+	git pull 
+	shopt -s nocasematch
+	if [[ "$revision" != "head" ]]; then  
+	    git checkout $revision
+	fi
+	cd -
+    else
+	git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git $openair_path
+	cd $openair_path
+	git checkout $branch
+	shopt -s nocasematch
+	if [[ "$revision" != "head" ]]; then  
+	    git checkout $revision
+	fi
+	cd -
+    fi
+    
+}
+juju_install_kernel(){
+
+    if [ "$machine_type"  == "lxc" -o "$machine_type" == "docker" ]; then
+	juju-log "Can't install the required kernel in $machine_type env. Proceed with the current kernel."
+    else 
+	if  [ "$machine_type"  == "" ] ; then 
+	    juju-log "Please install kerenel version 3.19 on the host".
+	else 
+	    check_current_kernel
+	    if [[ $REQUIRED_KERNEL_IS_INSTALLED == false ]]; then
+		if [ "$(cat $CHARM_DIR/.reboot)" != "reboot" ]; then  
+		    juju-log "installing the required kernel and reboot"
+		    status-set maintenance "installing the required kernel and rebooting"
+		    install_required_kernel
+  		    echo "reboot" > $CHARM_DIR/.reboot 
+		    juju-reboot --now
+		else 
+		    juju-log "Can't install the required kernel. Proceed with the current kernel."
+		fi 
+		#if we reboot now, the install is blocked here and reschedule after the reboot
+	    fi
+	fi
+    fi 
+}
+
+set_args(){
+    
+    if [ "$kernel" == "lowlatency" ]; then 
+	build_args="$build_args --disable-cpu-affinity --enable-deadline "
+	echo "$build_args"  > $CHARM_DIR/.build_args
+	cp $CHARM_DIR/.build_args $openair_path
+    fi
+
+    cp $CHARM_DIR/.execute $openair_path
+    cp $CHARM_DIR/.config_file_rrh $openair_path
+    cp $CHARM_DIR/.fh_if $openair_path
+    cp $CHARM_DIR/.fh_port $openair_path
+    cp $CHARM_DIR/.tr_mode $openair_path
+    cp $CHARM_DIR/.loopback $openair_path
+    
+}
+
+build_rrh(){
+    status-set maintenance "RF check, package installation, and build process for RRH GW"
+
+    if [ "$hw" == "usrp" -o "$hw" == "USRP" ]; then
+	
+	echo "$config_file_usrp" > $CHARM_DIR/.config_file_rrh
+	cp $CHARM_DIR/.config_file_rrh $openair_path
+	
+	$build_path/build_oai -I -w USRP
+	echo "$build_path/build_oai -C -c --RRH -t ETHERNET -w USRP `echo $build_args`"
+	$build_path/build_oai -C -c --RRH -t ETHERNET -w USRP `echo $build_args`
+	
+    elif [ "$hw" == "bladerf" -o "$hw" == "BLADERF" ]; then
+	
+	echo "$config_file_bladerf" > $CHARM_DIR/.config_file_rrh
+	cp $CHARM_DIR/.config_file_rrh $openair_path
+	
+	$build_path/build_oai -I -w BLADERF
+	echo "$build_path/build_oai -C -c --RRH -t ETHERNET -w BLADERF `echo $build_args`"
+	$build_path/build_oai -C -c --RRH -t ETHERNET -w BLADERF `echo $build_args`
+	
+    elif [ "$hw" == "sodera" -o "$hw" == "lmssdr" ]; then
+	
+	if [ "$config_file" == "default" ]; then 
+	    echo "$config_file_sodera_path/$config_file_default" > $CHARM_DIR/.config_file_rrh
+	else 
+	    echo "$config_file_sodera_path/$config_file" > $CHARM_DIR/.config_file_rrh
+	fi 
+	cp $CHARM_DIR/.config_file_rrh $openair_path
+	
+	$build_path/build_oai -I -w LMSSDR
+	echo "$build_path/build_oai -C -c --RRH -t ETHERNET -w LMSSDR `echo $build_args`"
+	$build_path/build_oai -C -c --RRH -t ETHERNET -w LMSSDR `echo $build_args`
+	
+    elif [ "$hw" == "exmimo" -o "$hw" == "EXMIMO" ]; then
+	
+	echo "$config_file_exmimo" > $CHARM_DIR/.config_file_rrh
+	cp $CHARM_DIR/.config_file_rrh $openair_path
+	
+	$build_path/build_oai -I 
+	echo "$build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`"
+	$build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`
+    else 
+	juju-log -l WARNING "Hardware option not valid, switching to EXMIMO"
+	hw="exmimo"
+	echo "$hw" > $CHARM_DIR/.hw
+	
+	echo "$config_file_exmimo" > $CHARM_DIR/.config_file_rrh
+	cp $CHARM_DIR/.config_file_rrh $openair_path
+	
+	$build_path/build_oai -I 
+	echo "$build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`"
+	$build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`
+    fi
+    
+}
+
 set -eux
 
 export DEBIAN_FRONTEND=noninteractive
@@ -67,143 +219,16 @@ echo "$revision" > $CHARM_DIR/.revision
 echo "$kernel"      >  $CHARM_DIR/.kernel
 
 
-gitAlreadyInstalled=$(dpkg --get-selections git 2>/dev/null | grep -c 'install') || true
-if [ ! $gitAlreadyInstalled -eq 1 ]; then 
-   # If git is NOT installed
-   apt-get install -y --force-yes git 
-   # Ensure necessary git dependency exist.
-fi
-atAlreadyInstalled=$(dpkg --get-selections at 2>/dev/null | grep -c 'install') || true
-if [ ! $atAlreadyInstalled -eq 1 ]; then 
-   # If at command is NOT installed
-   apt-get install -y --force-yes at
-   # Ensure at command exists to let juju reschedule this hook after rebooting the machine.
-fi
-virtwhatAlreadyInstalled=$(dpkg --get-selections virt-what 2>/dev/null | grep -c 'install') || true
-if [ ! $virtwhatAlreadyInstalled -eq 1 ]; then 
-   apt-get install -y --force-yes virt-what
-fi
+install_packages
 machine_type=`virt-what`
 
-juju-log "Fetching and installing openairinterface RRH GW for $hw"
-status-set maintenance "Fetching and installing openairinterface RRH GW"
+clone_repro
 
+juju_install_kernel
 
-echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
+set_args
 
-#everytime refresh the installation 
-if [ -d "$openair_path"  ]; then
-   #juju-log "Removing the installation directory"
-   #rm -rf $openair_path
-    juju-log "Updating the installation directory"
-    cd $openair_path 
-    git reset --hard HEAD
-    git checkout $branch 
-    git pull 
-    shopt -s nocasematch
-    if [[ "$revision" != "head" ]]; then  
-       git checkout $revision
-    fi
-    cd -
-else
-    git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git $openair_path
-    cd $openair_path
-    git checkout $branch
-    shopt -s nocasematch
-    if [[ "$revision" != "head" ]]; then  
-       git checkout $revision
-    fi
-    cd -
-fi
-
-if [ "$kernel" == "lowlatency" ]; then 
-    build_args="$build_args --disable-cpu-affinity --enable-deadline "
-    echo "$build_args"  > $CHARM_DIR/.build_args
-    cp $CHARM_DIR/.build_args $openair_path
-fi
-
-if [ "$machine_type"  == "lxc" -o "$machine_type" == "docker" ]; then
-    juju-log "Can't install the required kernel in $machine_type env. Proceed with the current kernel."
-else 
-    if  [ "$machine_type"  == "" ] ; then 
-	juju-log "Please install kerenel version 3.19 on the host".
-    else 
-	check_current_kernel
-	if [[ $REQUIRED_KERNEL_IS_INSTALLED == false ]]; then
-	    if [ "$(cat $CHARM_DIR/.reboot)" != "reboot" ]; then  
-		juju-log "installing the required kernel and reboot"
-		status-set maintenance "installing the required kernel and rebooting"
-		install_required_kernel
-  		echo "reboot" > $CHARM_DIR/.reboot 
-		juju-reboot --now
-	    else 
-		juju-log "Can't install the required kernel. Proceed with the current kernel."
-	    fi 
-	    #if we reboot now, the install is blocked here and reschedule after the reboot
-	fi
-    fi
-fi 
-
-cp $CHARM_DIR/.execute $openair_path
-cp $CHARM_DIR/.config_file_rrh $openair_path
-cp $CHARM_DIR/.fh_if $openair_path
-cp $CHARM_DIR/.fh_port $openair_path
-cp $CHARM_DIR/.tr_mode $openair_path
-cp $CHARM_DIR/.loopback $openair_path
-
-status-set maintenance "RF check, package installation, and build process for RRH GW"
-
-if [ "$hw" == "usrp" -o "$hw" == "USRP" ]; then
-    
-    echo "$config_file_usrp" > $CHARM_DIR/.config_file_rrh
-    cp $CHARM_DIR/.config_file_rrh $openair_path
-    
-    $build_path/build_oai -I -w USRP
-    echo "$build_path/build_oai -C -c --RRH -t ETHERNET -w USRP `echo $build_args`"
-    $build_path/build_oai -C -c --RRH -t ETHERNET -w USRP `echo $build_args`
-
-elif [ "$hw" == "bladerf" -o "$hw" == "BLADERF" ]; then
- 
-    echo "$config_file_bladerf" > $CHARM_DIR/.config_file_rrh
-    cp $CHARM_DIR/.config_file_rrh $openair_path
-    
-    $build_path/build_oai -I -w BLADERF
-    echo "$build_path/build_oai -C -c --RRH -t ETHERNET -w BLADERF `echo $build_args`"
-    $build_path/build_oai -C -c --RRH -t ETHERNET -w BLADERF `echo $build_args`
-
-elif [ "$hw" == "sodera" -o "$hw" == "lmssdr" ]; then
-
-    if [ "$config_file" == "default" ]; then 
-	echo "$config_file_sodera_path/$config_file_default" > $CHARM_DIR/.config_file_rrh
-    else 
-	echo "$config_file_sodera_path/$config_file" > $CHARM_DIR/.config_file_rrh
-    fi 
-    cp $CHARM_DIR/.config_file_rrh $openair_path
-    
-    $build_path/build_oai -I -w LMSSDR
-    echo "$build_path/build_oai -C -c --RRH -t ETHERNET -w LMSSDR `echo $build_args`"
-    $build_path/build_oai -C -c --RRH -t ETHERNET -w LMSSDR `echo $build_args`
-
-elif [ "$hw" == "exmimo" -o "$hw" == "EXMIMO" ]; then
-    
-    echo "$config_file_exmimo" > $CHARM_DIR/.config_file_rrh
-    cp $CHARM_DIR/.config_file_rrh $openair_path
-    
-    $build_path/build_oai -I 
-    echo "$build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`"
-    $build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`
-else 
-    juju-log -l WARNING "Hardware option not valid, switching to EXMIMO"
-    hw="exmimo"
-    echo "$hw" > $CHARM_DIR/.hw
-    
-    echo "$config_file_exmimo" > $CHARM_DIR/.config_file_rrh
-    cp $CHARM_DIR/.config_file_rrh $openair_path
-    
-    $build_path/build_oai -I 
-    echo "$build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`"
-    $build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO `echo $build_args`
-fi
+build_rrh
 
 #add the rrh-gw init
 juju-log "Add rrh-gw init script"
